[tool.poetry]
name = "restraction"
version = "0.1.0"
description = ""
authors = ["Hinrik S. Gudmundsson"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
datasets = "^3.5.0"
trl = "^0.16.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
